### ISSUE TITLE
Ability to access the added keys that are captured from the lambda context. (eg. coldstart)

### ISSUE THREAD

**Issue by Nxtra** [awslabs/aws-lambda-powertools-python#114]
**Is your feature request related to a problem? Please describe.**
I'd like to have a metric that visualises the number of cold starts.

**Describe the solution you'd like**
I want to read the coldstart true / false from the context that is added to the logger when using `@logger.inject_lambda_context`. That would mean I can build a metric based on this value.

**Describe alternatives you've considered**
I could implement a way to figure out a coldstart myself by having a variable setup in the initialisation code

**Comment by heitorlessa** [comment]
Hey again ;)

 Have you seen this Metrics feature to create a cold start metric for you?


https://awslabs.github.io/aws-lambda-powertools-python/core/metrics/#capturing-cold-start-metric

 Does that help? If not, I’d love to hear what the dev experience
should look like.

 PS: Cold start metrics are also adding function_name dimension, so we’re
thinking of removing that in the next minor version to avoid confusion when
visualising other metrics. Instead, add function_name in the metrics
metadata, otherwise you end up with a container of metrics named (service,
function_name) for when it’s a cold start.

**Comment by Nxtra** [comment]
Nice that's what I was looking for.
And I was so proud of my workaround using a variable that is set when the function is first initialised. XD
Turns out to be unnecessary. You already have it.
Resolved.
