### ISSUE TITLE
Refactor Parser docs code snippets

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-python#1371]

**Comment by hakanson** [comment]
This was exactly what I was looking for, and worked great.  Some comments on making the docs better.

In the [Parsing event](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#parsing-events) section, the `event_parser decorator` calls out:

> `event_parser` decorator will throw a `ValidationError` if your event cannot be parsed according to the model.

but this has an implication on the Lambda response that could be more explicitly called out.  I mainly noticed this because it caused a change in my unit test behavior.

The next section `parse function` example does solve this, but by using `def my_function():` instead of `def handler(event: Order, context: LambdaContext):` as in the previous example, this was harder (for me) to realize this was the example I really wanted.

Also, the first example had the order: classes, hander def, payload def, invoke hander - and the next example was: classes, payload, function def, (no invoke example).  The first example seemed to flow better, and these could be normalized.

**Comment by leandrodamascena** [comment]
Hey @hakanson! Hope you are well.

Now I'm refactoring all the docs, examples and adding more details in general. I'm planning to send a PR tomorrow or Wednesday..
After submitting the PR, can I tag you to help me validate and improve it?

**Comment by hakanson** [comment]
> Hey @hakanson! Hope you are well.
> 
> 
> 
> Now I'm refactoring all the docs, examples and adding more details in general. I'm planning to send a PR tomorrow or Wednesday..
> 
> After submitting the PR, can I tag you to help me validate and improve it?

Yes, I have some commitments coming but will do my best.
