### ISSUE TITLE
Feature request: Span operation names to include class name

### ISSUE THREAD

**Issue by petarlishov** [awslabs/aws-lambda-powertools-python#1454]
### Use case

Currently if you add a span to a function with the provided annotation `tracer.capture_method`, the created span only uses the function's name. So if it is a function within a class, say for example some implementation of an abstract class, it is hard to realise which particular method was called as there are multiple classes with the same method.

### Solution/User Experience

If we include the class in the operation name of the span, I think that would be helpful. I am not really sure if I won't start  doscussion on whether the full module name needs included as well, but I think in terms of usefulness, asking for the class name is a sensible middle ground that would cover most people's use cases (hopefully others don't often have the same class name within different modules of the same project)

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by rubenfonseca** [comment]
Hi @petarlishov thanks for opening this. We're actively trying to prioritize this issue for our v2 release in the next couple of weeks. We will also apply a [similar fix to the idempotency utility](https://github.com/awslabs/aws-lambda-powertools-python/issues/1330). Stay tuned :)

**Comment by leandrodamascena** [comment]
Hi @petarlishov, how are you? I'm working on it and fixing some issues in the tests before opening a PR. This feature will be included in [v2](https://github.com/awslabs/aws-lambda-powertools-python/issues/1459) and it will take a few weeks for us to release this new version.

I was wondering if this feature is blocking something you need to work with, if so we can find a solution (as a feature flag) where you can set a custom name for the `subsegment` instead of getting this [automatically](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/tracing/tracer.py#L511).

Please let us know if you are comfortable waiting for v2 to be released or if an immediate solution would help your work further.

Thank you

**Comment by heitorlessa** [comment]
Closing as we're wrap to launch V2
