### ISSUE TITLE
Bug: Serverless Application Repository Extra Layer Does not Contain Pydantic

### ISSUE THREAD

**Issue by lhendrick-t10** [awslabs/aws-lambda-powertools-python#1519]
### Expected Behaviour

Attaching the extras layer to a Lambda Function should enable it to use pydantic functionality for the Parser.

### Current Behaviour

Attempting to invoke the Lambda returns the following error:

```json
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'pydantic'",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "be591aa8-0c3b-477c-ac86-bc13d602cf5a",
  "stackTrace": []
}
```

Downloading the layer provides me with a 10.1 MB zip file, where the docs say to expect a 22MB compressed file

Attached Code Snippet is a minimal example

### Code snippet

```python
from aws_lambda_powertools.utilities.parser import event_parser, BaseModel, envelopes

class TestClass(BaseModel):
    some: str
    data: str
    item: str


@event_parser(model=TestClass, envelope=envelopes.EventBridgeEnvelope)
def lambda_handler(event: TestClass, context):
    print(event.some)
```

### Possible Solution

Rebuild and deploy layer with pydantic dependencies

### Steps to Reproduce

- Deploy SAR "extras" layer into Account
    - ARN: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer-extras
- Attach to a Lambda Function that attempts to use the event parser

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Serverless Application Repository (SAR) App

**Comment by lhendrick-t10** [comment]
Similar to [this](https://github.com/awslabs/aws-lambda-powertools-python/issues/290) issue

**Comment by heitorlessa** [comment]
@am29d could you help us on this?

**Comment by am29d** [comment]
Another mystery with the layers appears. 

Due to [recent](https://github.com/awslabs/aws-lambda-powertools-python/commit/d344c794e3e3bcdfd448fe18cda2ca60cdedf1cf) revert of `poetry.lock` we have a version mismatch between the poetry configuration file and release tag. Our SAR pipeline assumes the version in this file is correct, which means equals to the git tag we use. So if we checkout the repo with specific tag, say `v1.29.1` and run `poetry build` it should build a package for version `1.29.1`, which is not the case at the moment (it creates a package for 1.26.6). 

This caused dependency resolution issues during extras package installation:

> Dependency walk failed at typing-extensions (>=3.7.4.3)

The biggest problem is that it failed silently and the tests did not catch the missing package in a test deployment. I will add additional mechanism with checks and tests to ensure it won't happen in the future. 

I have checked the last 10 previous releases and only the last version is affected (1.29.1)

**Comment by rubenfonseca** [comment]
@lhendrick-t10 thanks for reporting this! @am29d found and fixed the underlying issue, and we'll release 1.29.2 in the next hour to fix the SAR layer

**Comment by lhendrick-t10** [comment]
Awesome! Thanks @am29d and @rubenfonseca, really appreciate all the help!

**Comment by am29d** [comment]
Hey @lhendrick-t10 , sorry for the release delay, but the new version 1.29.2 is now deployed to SAR and the issue has been fixed.
