### ISSUE TITLE
Bug: when installing powertools from Pypi - pydantic is not added

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1645]
### Expected Behaviour

The powertools layer includes pydantic. 
I expect that when i install powertools, it will bring pydantic as a dependancy.

### Current Behaviour

It does not at the moment.

Removed pydantic from pip file. left powertools.
Got: E   ModuleNotFoundError: No module named 'pydantic'

### Code snippet

```python
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
aws-lambda-powertools = "*"

[requires]
python_version = "3.9"
```

### Steps to Reproduce

pip install aws-lambda-powertools

### AWS Lambda Powertools for Python version

2.0.0

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by ran-isenberg** [comment]
when adding aws-lambda-powertools= {extras = ["all"],version = "*"} it works.

**Comment by heitorlessa** [comment]
That's expected behaviour @ran-isenberg :) we described that in the [V2 Release notes](https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0), [Install docs](https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/#install), and [upgrade guide](https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/upgrade/#first-steps).

We removed **all dependencies** - 70% of Powertools only rely on AWS SDK/JMESPath that is available in the Lambda Runtime. For Lambda Layer though, we include all of them, remove all dependencies available in the Lambda Runtime, and optimize Pydantic with Cython.

If there's a way that we can make this more explicit, please do let us know!

Closing.

---

**Release notes**

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/3340292/198563929-27d957b5-4274-4da5-bdec-eba41de70cbc.png">

**Upgrade guide**

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/3340292/198564014-985e18da-c8a3-48ce-b012-fa925fda4c3a.png">

**Install section**

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/3340292/198564038-9ca534df-698f-48b1-a662-7a18b307c965.png">
