### ISSUE TITLE
Bug:  when installing powertools from Pypi - aws_xray_sdk is not added 

### ISSUE THREAD

**Issue by ran-isenberg** [awslabs/aws-lambda-powertools-python#1647]
### Expected Behaviour

aws_xray_sdk is imported and does not fail tests/imports . to my understating, it's part of the powertools lambda layer.

### Current Behaviour

aws_xray_sdk module not found error.

### Code snippet

```python
aws_xray_sdk module not found error.
```

### Possible Solution

manually add aws_xray_sdk to pip/toml file.

### Steps to Reproduce

pip install aws-lambda-powertools 

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by rpmcginty** [comment]
My guess is that you are using the V2.0 release, where they reduced the total size of the package and did so by removing bloated dependencies like aws xray in the default install. 

https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0#package-size-reduction-by-976

> We updated each documentation to emphasize when an additional dependency is required ([Tracer](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/tracer/), [Validation](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/validation/) and [Parser](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/)). If you [prefer to install all of them](https://awslabs.github.io/aws-lambda-powertools-python/2.0.0a2/#install), use pip install aws-lambda-powertools[all].


I think the solution is to just specify the dependency as `aws-lambda-powertools[all]`

**Comment by ran-isenberg** [comment]
yep, i changed it to aws-lambda-powertools= {extras = ["all"],version = "*"} and it works.
thanks for the heads up!

**Comment by heitorlessa** [comment]
That's expected behaviour @ran-isenberg :) we described that in the [V2 Release notes](https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.0.0), [Install docs](https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/#install), and [upgrade guide](https://awslabs.github.io/aws-lambda-powertools-python/2.0.0/upgrade/#first-steps).

We removed **all dependencies** - 70% of Powertools only rely on AWS SDK/JMESPath that is available in the Lambda Runtime. For Lambda Layer though, we include all of them, remove all dependencies available in the Lambda Runtime, and optimize Pydantic with Cython.

If there's a way that we can make this more explicit, please do let us know!

Closing.

---

**Release notes**

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/3340292/198563929-27d957b5-4274-4da5-bdec-eba41de70cbc.png">

**Upgrade guide**

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/3340292/198564014-985e18da-c8a3-48ce-b012-fa925fda4c3a.png">

**Install section**

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/3340292/198564038-9ca534df-698f-48b1-a662-7a18b307c965.png">
