### ISSUE TITLE
Bug: Subsegment ssm discarded due to Lambda worker still initializing

### ISSUE THREAD

**Issue by 94Sip** [awslabs/aws-lambda-powertools-python#1680]
### Expected Behaviour

The expected behavior would be to not receive this warning message

### Current Behaviour

- Receiving an intermittent warning, stating "Subsegment ssm discarded due to Lambda worker still initializing", followed by another warning stating "No subsegment to end." These appear to be raised by the powertools Parameters utility.
- I am doing the parameter retrieval before the lambda handler (global scope) since this will not change very often, regardless of execution environment, as demonstrated below.

### Code snippet

```python
from aws_lambda_powertools.utilities import parameters
import boto3

config = Config(
   retries = {
      'max_attempts': 15,
      'mode': 'standard'
   }
)
client=boto3.client('rekognition', config=config)
model_arn=parameters.get_parameter('/RekCL/MODEL_ARN', max_age=300)

def lambda_handler(event, context):
  try:
        response = client.detect_custom_labels(
            ProjectVersionArn=model_arn,
            Image={'S3Object':{'Bucket':bucket,'Name':photo}})

 # etc...
```

### Possible Solution

Please see this: https://github.com/aws/aws-xray-sdk-python/issues/331

I believe there is a check here, but I don't see anything in the powertools docs that says I need to have x-ray enabled.

### Steps to Reproduce

retrieve a parameter in a lambda function, with global scope (before lambda handler)

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

**Comment by heitorlessa** [comment]
Hi @94Sip thanka for flagging this - IIRC this is an issue in X-Ray SDK which hasn't been resolved yet (I'll use this as a basis for a repro).

In the meantime, you can safely add the get_parameter inside the handler, because only the first call will be made to SSM.

We keep that in-memory and it'll only fetch another call if Lambda spins up another container (concurrency), which is also true for a new cold start to happen.

**Comment by 94Sip** [comment]
A few more updates:

This lambda is being orchestrated by a Step Function that has x-ray tracing enabled. I have enabled x-ray on the lambda function AND added the appropriate policy, as described here: https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html

Still receiving the intermittent warning.

**Comment by 94Sip** [comment]
> Hi @94Sip thanka for flagging this - IIRC this is an issue in X-Ray SDK which hasn't been resolved yet (I'll use this as a basis for a repro).
> 
> In the meantime, you can safely add the get_parameter inside the handler, because only the first call will be made to SSM.
> 
> We keep that in-memory and it'll only fetch another call if Lambda spins up another container (concurrency), which is also true for a new cold start to happen.

Thank you for this quick reply - moving the call to the handler appears to have resolved this warning being thrown.

**Comment by heitorlessa** [comment]
Thank you, that helps to investigate it later.

From memory, this was an issue that the root segment wasn't available yet for the SDK to pick up at container initialisation (what technically is a cold start). Hence why it shouldn't happen after the handler is called.

What X-Ray SDK was trying was using a DummySegment that later would be converted to account for eventual consistency -- it's a tricky thing.

That said, in your case, get_parameter can be safely used inside the handler. 

> Not your use case but as FYI until our new parameter docs is finished.


It's also recommended for optimal cache invalidation for frequently updated parameters. 

This is because we only fetch a new one on the next call, where the parameter expired, to not "eat" your Lambda resources with a background thread due to CPU slicing.

**Comment by heitorlessa** [comment]
Did some investigation here and [X-Ray team reverted their decision to fail](https://github.com/aws/aws-xray-sdk-python/issues/129) fast IF a trace is still not available to attach an application subsegment yet. Instead, it [logs the warning you see in your code](https://github.com/aws/aws-xray-sdk-python/blob/7ec8c59e2d61d13cb223f50f6a4973c51f8c5da5/aws_xray_sdk/core/lambda_launcher.py#L75) to prevent crashing customers' function, hence why inside the Handler always works.

As this might be solved in the future by Lambda, or not due to eventual consistency, I'm going to close this issue as there isn't much we can do from our side. While we could try to do a double verification and hold the subsegment data for a random time, it could lead to a non-deterministic behaviour.

Thank you and let us know otherwise!
