### ISSUE TITLE
Parser (Pydantic) re-export Pydantic errors for data model validation 

### ISSUE THREAD

**Issue by kPOWz** [awslabs/aws-lambda-powertools-python#1687]
### Use case

When writing validators and root validators it is useful to keep error formats consistent with the Pydantic `TypeError`s and `ValueError`s from the Pydantic errors module

Due to how Pydantic is packaged, these errors are not exported by https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/parser/pydantic.py#L5 

https://awslabs.github.io/aws-lambda-powertools-python/2.1.0/utilities/parser/#data-model-validation

### Solution/User Experience

re-export the LPT packaged Pydantic errors module under `from aws_lambda_powertools.utilities.parser.pydantic.errors`

ensure this will still work smoothly after [switch to rust / pydantic core ](https://github.com/pydantic/pydantic/pull/4516)

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by heitorlessa** [comment]
Hey @kPOWz, would this work? 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/3340292/202200785-bde7d9bc-4a9a-4eb8-9250-110196def765.png">

Looking at Pydantic exported symbols, there doesn't seem to be any clash so I can export them directly too.

https://github.com/awslabs/aws-lambda-powertools-python/pull/1728/files#diff-802361d017af63e8fc18b5df568bbdfc17800ab8b90ef502a64a907ce4ef917bR9

**Comment by heitorlessa** [comment]
[Just read Pydantic V2 plan](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#removed-features-limitations) and the only breaking change it seems to apply here is `parse_raw` that we use in Parser. I couldn't find a specific mention on errors packaging.

I'll go ahead and merge the errors exposing, since `parser.pydantic.errors` wouldn't work as it's not a package and doesn't seem to need to be.

Because it's a major version, we will come to that when we need to cross that bridge. I think there's a great chance in the future to make Pydantic built-in in Powertools to ease developing certain features like Feature Flags - the benchmarks and reduced package size look fantastic, but we need to apply due-diligence and weigh its pros/cons as usual.
