### ISSUE TITLE
improve warning message on Capturing ColdStart metrics

### ISSUE THREAD

**Issue by amirkaws** [awslabs/aws-lambda-powertools-python#1926]
### Expected Behaviour

When metric decorator is added on top of the lambda handler to capture Cold Start metric, we should not get any warning message for cold or warm lambda invocation.

### Current Behaviour

When metric decorator is added on top of the lambda handler to capture Cold Start metric, we get a warning message. `No metrics to publish, skipping`. 

### Code snippet

```python
@metrics.log_metrics(capture_cold_start_metric=True)
def lambda_handler(event: dict, context: LambdaContext):
    ...
```

### Steps to Reproduce

- Add @metrics.log_metrics(capture_cold_start_metric=True) to the lambda handler
- Ensure no more metrics is added in the lambda
- Run Lambda
- `UserWarning: No metrics to publish, skipping` appears in function log

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

Lambda Layers

**Comment by rubenfonseca** [comment]
Hi @amirkaws thank you so much for opening this issue! We did a check on the code, and as we understand it, the feature works correctly. We think the confusion is that `capture_cold_start` creates a separate EMF Blob because it uses a different Metric dimensions (to avoid data loss). It happens regardless if there are application metrics or not, as long as it's a cold start.

![image](https://user-images.githubusercontent.com/10713/218748441-3899a920-a451-4582-ac5f-f519647f05da.png)

The "empty metrics" warning is expected if there are no metrics being added to be flushed. Cold start metrics will **always** be flushed if there is a cold start:

![image](https://user-images.githubusercontent.com/10713/218748795-ef30cc75-164b-414c-b344-2c782dc0ee9d.png)

Does this help explain the behavior you're seeing?

**Comment by amirkaws** [comment]
Hi @rubenfonseca, thanks for your prompts response. From the end user prospective, if capturing the ColdStart is the only metric I am interested in, Should I get warning, which is the case here?

**Comment by rubenfonseca** [comment]
The reason we add the warning and print what seems to be an empty metric warning is that it could be useful to detect bugs on the customer code (we already had cases with conditional metrics). In those cases, there could be useful metric metadata which would be lost otherwise. 

Having said that, you have a point that the current DX could be misleading or create confusion. Would it make sense to change the warning message to be more explicit? "No application metrics to publish, skipping".

**Comment by amirkaws** [comment]
Sure no problem, I just wanted to ensure that's expected results, customer capturing cold start metrics and we are warning them metrics to publish. As you mentioned may be more specific message would help. thanks

**Comment by rubenfonseca** [comment]
@amirkaws we were discussing this internally and come up with even a better one:

`No application metrics to publish. The cold-start metric may be published if enabled. If application metrics should never be empty, consider using "raise_on_empty_metrics".`

WDYT?

**Comment by heitorlessa** [comment]
> @amirkaws we were discussing this internally and come up with even a better one:
> 
> 
> 
> `No application metrics to publish. The cold-start metric may be published if enabled. If application metrics should never be empty, consider using "raise_on_empty_metrics".`
> 
> 
> 
> WDYT?

Much much better cc @dreamorosi too

**Comment by rubenfonseca** [comment]
@amirkaws if it's ok with you we would move forward with a PR to make this change

**Comment by dreamorosi** [comment]
Thank you for the mention, we currently don't have this warn behavior in our implementation. I'll open an issue so we can look into it, and if we do implement it, we'll use a similar wording to the one above.

**Comment by amirkaws** [comment]
LGTM, Thanks @rubenfonseca
