### ISSUE TITLE
Docs: create Example for usage of AppSync for Mutations

### ISSUE THREAD

**Issue by tb102122** [awslabs/aws-lambda-powertools-python#1953]
### What were you searching in the docs?

How to us the use the Framework for Mutations.

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/core/event_handler/appsync.md

### How can we improve?

add sample code for todo creation and update.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
Thanks a lot for creating the issue after our discussion on Discord: https://discord.com/channels/1006478942305263677/1006527338621710376/1078461122056814643

Taking your example as the base, I'll create a quick test to be extra sure it works as expected, then send a PR for the docs to get your review (and credit accordingly).

---

```python
@app.resolver(type_name="Mutation", field_name="createTodo")
@tracer.capture_method
def create_todo(
    id: str = "",  # noqa AA03 VNE003 shadows built-in id to match query argument, e.g., createTodo(id: "some_id")
) -> Todo:
    logger.info(f"Create Todo {id}")
    todos: Response = requests.put(f"https://jsonplaceholder.typicode.com/todos/{id}") // NOT SURE what to DO!
    todos.raise_for_status()

    return todos.json() 
```

**Comment by heitorlessa** [comment]
hey @tb102122 just created a draft PR improving the example, and the wording around `GraphQL Type and Field` in the context of event resolution.

Please let me know your thoughts. I thought it'd be too much to add a mutation json sample given the real estate we're dealing with - let me know otherwise!

https://github.com/awslabs/aws-lambda-powertools-python/pull/1964
