### ISSUE TITLE
Docs: Fix local tests example in the Idempotency Testing Your Code section

### ISSUE THREAD

**Issue by leandrodamascena** [awslabs/aws-lambda-powertools-python#2072]
### What were you searching in the docs?

Improve the documentation by changing the example to be more realistic.

### Is this related to an existing documentation section?

Idempotency

### How can we improve?

Changing documentation

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
removing triage...

**Comment by heitorlessa** [comment]
only last comment before merging is that this part shouldn't work, please double check in case I'm wrong: https://github.com/awslabs/aws-lambda-powertools-python/pull/2073/files#diff-e612f95a3dbd33cabab2e49899653b8cc5d5e809bfad45aa54cdee41d22e5808R1253

**Reason**. Unless AWS SDK changed, the DynamoDB client wouldn't connect to DynamoDB Local because the client isn't being replaced, therefore it'd use the real DynamoDB external endpoint.
