### ISSUE TITLE
Bug: PreSignUpTriggerEvent  'dict' object has no attribute 'response'

### ISSUE THREAD

**Issue by airmonitor** [awslabs/aws-lambda-powertools-python#2217]
### Expected Behaviour

Event response correctly updated.
keys autoConfirmUser and autoVerifyEmail set to True

### Current Behaviour

[ERROR] AttributeError: 'dict' object has no attribute 'response'
Traceback (most recent call last):
  File "/var/task/handler.py", line 23, in handler
    event.response.auto_confirm_user = True

### Code snippet

```python
# -*- coding: utf-8 -*-
from aws_lambda_powertools.utilities.data_classes.cognito_user_pool_event import PreSignUpTriggerEvent
from aws_lambda_powertools.utilities.typing import LambdaContext
from utils.observability import logger, tracer, metrics


@metrics.log_metrics(capture_cold_start_metric=True)
@logger.inject_lambda_context(log_event=True)
@tracer.capture_lambda_handler
def handler(event: PreSignUpTriggerEvent, context: LambdaContext):
    """Update a Cognito Pre Sign Up event to auto-confirm the user.

    This function is called by the Cognito service when a user signs up.
    The function updates the event to auto-confirm the user.

    This function is meant to be used as a Lambda function.

    For more information, see:
    https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html

    :param event: The event passed to the Lambda function.
    :param context: The Lambda context.
    :return: The event to be passed to the next handler.
    :raises: Exception.
    """
    logger.debug(event)

    # Update the event to auto-confirm the user.
    event.response.auto_confirm_user = True
    event.response.auto_verify_email = True

    return event
```

### Steps to Reproduce

1. Create AWS Cognito User Pool
2. Assign pre_sign_up trigger to a lambda function that use above code snippet

### AWS Lambda Powertools for Python version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Hi, @airmonitor! Thanks for opening this issue! Actually, this is not a bug, it is the expected behavior of your code. Below I bring some items to help explain how your code is working.

- You are trying to access the `response` field as an object (`event.response`), but every event payload in Lambda is a [JSON](https://docs.aws.amazon.com/lambda/latest/operatorguide/payload.html) and you can't access a `dict` key like this.
- To convert the event into an object, add the [event_source decorator](https://awslabs.github.io/aws-lambda-powertools-python/2.15.0/utilities/data_classes/#utilizing-the-data-classes) in the `lambda_hanlder` function. But adding this you will have an `object` and no longer a `dict`, that is, you cannot do a `return event` because Lambda will not be able to serialize an object of type `PreSignUpTriggerEvent` on return.
- In your case, you just want to receive the `Pre sign-up Lambda trigger` event and add keys in the response field to continue with your authentication flow, so I suggest simplifying your code to make it functional. You can also use the [Parser](https://awslabs.github.io/aws-lambda-powertools-python/2.15.0/utilities/parser/) or [Validation](https://awslabs.github.io/aws-lambda-powertools-python/2.15.0/utilities/validation/) utility to validate the event payload and make the code more resilient.

```python
# -*- coding: utf-8 -*-
from aws_lambda_powertools.utilities.data_classes.cognito_user_pool_event import PreSignUpTriggerEvent
from aws_lambda_powertools.utilities.typing import LambdaContext
from utils.observability import logger, tracer, metrics

@metrics.log_metrics(capture_cold_start_metric=True)
@logger.inject_lambda_context(log_event=True)
@tracer.capture_lambda_handler
def handler(event: PreSignUpTriggerEvent, context: LambdaContext):
    """Update a Cognito Pre Sign Up event to auto-confirm the user.

    This function is called by the Cognito service when a user signs up.
    The function updates the event to auto-confirm the user.

    This function is meant to be used as a Lambda function.

    For more information, see:
    https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html

    :param event: The event passed to the Lambda function.
    :param context: The Lambda context.
    :return: The event to be passed to the next handler.
    :raises: Exception.
    """
    event.get("response")["auto_confirm_user"] = True
    event.get("response")["auto_verify_email"] = True
    
    return event
```

I hope I helped and if you have any questions, please send them. Thank you.

**Comment by airmonitor** [comment]
Hey @leandrodamascena 

Thank you for explaining, it make a complete sense now. 
Sorry for false positive.

**Comment by heitorlessa** [comment]
We’re glad you opened an issue, Tomasz. Better safe than sorry ;)
