### ISSUE TITLE
Bug: High import time when importing `ApiGatewayResolver` because of `CodePipelineJobEvent`

### ISSUE THREAD

**Issue by darnley** [awslabs/aws-lambda-powertools-python#2352]
### Expected Behaviour

Do not import `CodePipelineJobEvent` when using `ApiGatewayResolver`, because the `CodePipelineJobEvent` will import `boto3` and huge increase the AWS Lambda Cold Start or prevent `boto3` from being called unexpectedly.

### Current Behaviour

When importing `ApiGatewayResolver`, it is importing `CodePipelineJobEvent` and `boto3`. However, `ApiGatewayResolver` does not need `boto3`.

This behaviour is increasing the AWS Lambda cold start. When I use a profiling tool in my machine, it seems that just to import it is costing ~200ms. When running on AWS with a 800MB runtime, it is costing ~400ms.

According to the profiling in this use case, importing `CodePipelineJobEvent` costed 61.9% of time, but it will not be used. That is weird.

![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4915497/0a0dbc16-0138-4913-8ec2-52f09a5b547d)
[profile.log](https://github.com/awslabs/aws-lambda-powertools-python/files/11619752/profile.log)

### Code snippet

```python
from aws_lambda_powertools.logging import Logger
from aws_lambda_powertools.metrics import Metrics
from aws_lambda_powertools.tracing import Tracer
from aws_lambda_powertools.event_handler.api_gateway import ApiGatewayResolver
```

### Steps to Reproduce

1. Put this code on a Python file;
2. Install `tuna` package using `pip install tuna`;
3. Run command
```bash
python -X importtime MY_SCRIPT.py 2> profile.log && tuna profile.log
```

Browser will appear with the profiling graph.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.9

### Packaging format used

PyPi

**Comment by darnley** [comment]
I do not know if this is a really "bug". I am just want help with this problem. :) Thank you.

**Comment by leandrodamascena** [comment]
Hi @darnley! Tudo bom? :smiley: 

Thank you very much for opening this issue, I really appreciate it!! Actually, I consider this a bug because it affects performance and you could demonstrate this. The problem here is how things happen in Python and not exactly a bug generated because of a wrong code or something like this. Let me try to explain what is going on and a possible solution.

We have the [Event Source Data Class ](https://awslabs.github.io/aws-lambda-powertools-python/2.15.0/utilities/data_classes/ )utility. This utility helps developers to transform the Lambda Payload into a dictionary-like object, what makes easy to access properties and nested items. The `ApiGatewayResolver` takes advantage of the DataClass utility to make the code cleaner and this is where the problem occurs. 

We are not directly importing the `CodePipelineJobEvent` class in the `ApiGatewayResolver`, but In this [line](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/event_handler/api_gateway.py#L31) we import 4 DataClass to use it in all event_handler resolvers, and the way Python works will always run` __init__.py` which exposes our entire DataClass module and consequently import boto3 from `CodePipelineJobEvent`.

I think we can solve this problem by changing the boto3 import in CodePipelineJobEvent class. We just need to import `boto3` if the customer explicitly wants to download an artifact from a CodePipeline Job and this is not a common case.

I've made some changes in my local environment and check this:
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/b003cfb2-895b-45f6-b888-5d3fbfd49938)
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/7d3e0649-007d-41cf-a43a-950a78fecd4d)
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/a219b874-2237-4d14-904e-375f39d91c6a)

If you have bandwidth, please send a PR to fix this, if not, don't worry, I can fix it. We are planning to release a version this week and this issue makes it more urgent than I expected. 

Muito obrigado :rocket:

**Comment by darnley** [comment]
Hello, @leandrodamascena! Tudo bem e com você? 😊

That sounds perfect and thanks for the explanation. I am sending a PR to fix this.
