### ISSUE TITLE
[I Made This]: Blog post on aspects of idempotency

### ISSUE THREAD

**Issue by valentindreismann** [awslabs/aws-lambda-powertools-python#2368]
### Link to your material

https://engineering.cloudflight.io/idempotency-the-right-way

### Description

Blog post outlining why idempotency is needed and how to design for it. 
Not going into technical details, but sticking to a conceptual/design level. 

### Preferred contact

Valentin Dreismann; https://www.linkedin.com/in/valentin-dreismann-69694b16a/

### Acknowledgment

- [X] I understand this content may be removed from Powertools for AWS Lambda (Python) documentation if it doesn't conform with the [Code of Conduct](https://aws.github.io/code-of-conduct)

**Comment by leandrodamascena** [comment]
Hello @valentindreismann! Thanks so much for sharing your work with us! We appreciate it when customers use Powertools and write about Powertools, that support is priceless to us.

I didn't get a chance to read this in detail because it's been such a busy day, but I'll read this blog post in detail on Monday and work on getting it into the community section.

Thank you

**Comment by heitorlessa** [comment]
hey @valentindreismann, firstly **thank you** for an excellent write up. Could you review that's a fair one-line summary before we merge?

https://github.com/awslabs/aws-lambda-powertools-python/pull/2425

**Comment by valentindreismann** [comment]
@heitorlessa, @leandrodamascena  yep, that one-line summary is fine. 
Off it goes :-)

**Comment by heitorlessa** [comment]
awesome, Leandro is off today so I asked Ruben to approve and we can get merged shortly :) 

Thank you one more time @valentindreismann !!
