### ISSUE TITLE
Feature request: Abilty to suppress IdempotencyAlreadyInProgressError

### ISSUE THREAD

**Issue by AlexChesters** [awslabs/aws-lambda-powertools-python#2490]
### Use case

We have a Lambda function where we have implemented Idempotency using `aws-lambda-powertools`. In our system it is expected behaviour that will we receive concurrent executions with the same payload. Currently this results in an exception (`IdempotencyAlreadyInProgressError`) being raised.

As this is expected behaviour for us, we wouldn't want an exception to occur.

### Solution/User Experience

If our Lambda function encountered this situation we would like it to wait for a period of time (ideally a period we could configure e.g. as an argument to `IdempotencyConfig`) before retrying to determine if the idempotency state is `COMPLETE`. I would expect an exception to be raised if the idempotency state is still `INPROGRESS` after this time expires.

I understand that the time our Lambda function would remain doing nothing is not ideal from a cost perspective, but this is an acceptable trade-off for us.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

**Comment by leandrodamascena** [comment]
Looking at this now.

**Comment by leandrodamascena** [comment]
Hi @AlexChesters! Thank you so much for opening this issue and bringing up your needs! I could simulate a data processing scenario with multiple clients invoking the same lambda with the same payload, using that entire payload as a key to compute the `Idempotency Key` and getting the `IdempotencyAlreadyInProgressError`.

But I'm very curious about the scenario where you are using many invocations with the same payload and you use the entire payload as a key. Could you use a composite key to calculate the `idempotency key`, for example?
I'm concerned if this is a general use case or a very specific one because if we take this validation away we could have problems not mapped so far.

My suggestion for moving forward with this issue is as follows:

1 - I will add the `need-customer-feedback` label
2 - Can you send an email to <aws-lambda-powertools-feedback at amazon dot com> and I'll send you date slots for us to have a meeting? We are very curious to hear your use case and this meeting could be very productive.

Thanks

**Comment by AlexChesters** [comment]
Hey!

> But I'm very curious about the scenario where you are using many invocations with the same payload and you use the entire payload as a key. Could you use a composite key to calculate the idempotency key, for example?

I might not have been clear earlier, we are already using a composite key (https://docs.powertools.aws.dev/lambda-python/latest/utilities/idempotency/#choosing-a-payload-subset-for-idempotency) to calculate the idempotency key - we aren't using the entire payload.

To add some more context this system receives events from various AWS and custom services and sends them to different staff members through channels such as Slack, Email etc.

In particular the area we are looking at idempotency is a Lambda which is triggered by [AWS Health events](https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html) for every AWS account in our organisation (several hundred).

We've identified two items from the payload (the event ARN and the communication ID) which we would like to use to to dedupe these events. Our reasoning here is that if a user is subscribed to notifications for 5 accounts, we wouldn't need to send the same communication 5 times.

Hope that clarifies things, happy to have a further chat if useful - you can reach out to alex.chesters@bbc.co.uk 🙂

**Comment by leandrodamascena** [comment]
Thanks for the prompt response @AlexChesters! Now we have the whole scenario of how you are using idempotency and the reason why you want it. We may have some ideas on how to help you solve this problem and I think this will be easier if we have a meeting. I'll send you an email with some date slots to schedule this meeting.

Thank you very much.

**Comment by AlexChesters** [comment]
Sounds like a plan! Thank you 😄

**Comment by leandrodamascena** [comment]
Hello @AlexChesters! Thank you very much for attending the meeting and explaining the user case. As we agreed at that meeting, we will not suppress `IdempotencyAlreadyInProgressError` for now due to possible side effects. 

We are here to help in any way possible, so if you have any other requests please let us know and we can help.

I am closing the issue and feel free to reopen it if needed.
