### ISSUE TITLE
Bug: DynamoDBStreamEnvelope

### ISSUE THREAD

**Issue by stpsomad** [awslabs/aws-lambda-powertools-python#2851]
### Expected Behaviour

DynamoDBStreamEnvelope Parses records in NewImage and OldImage keys using your model.

### Current Behaviour

DynamoDBStreamEnvelope does not parse NewImage and OldImage as expected.

### Code snippet

```python
from aws_lambda_powertools.utilities.parser import (
    parse,
    BaseModel,
    envelopes,
)

payload = {
    "Records": [
        {
            "eventID": "918a97d90a2cc231d8f6cb54243c4666",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "eu-west-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1690369198.0,
                "Keys": {"id": {"S": "key1"}},
                "NewImage": {
                    "id": {"S": "key1"},
                    "value": {"N": "1"},
                },
                "SequenceNumber": "536700000000017398170841",
                "SizeBytes": 92,
                "StreamViewType": "NEW_IMAGE",
            },
            "eventSourceARN": "arn",
        }
    ]
}


class Item(BaseModel):
    id: str
    value: int

parse(model=Item, envelope=envelopes.DynamoDBStreamEnvelope, event=payload)
```

### Steps to Reproduce

Run the above code (inside or outside aws lambda).

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

### Debugging logs

```python
Traceback (most recent call last):
  File "test.py", line 34, in <module>       
    parse(model=Item, envelope=envelopes.DynamoDBStreamEnvelope, event=payload)
  File ".venv\lib\site-packages\aws_lambda_powertools\utilities\parser\parser.py", line 155, in parse
    return envelope().parse(data=event, model=model)
  File ".venv\lib\site-packages\aws_lambda_powertools\utilities\parser\envelopes\dynamodb.py", line 37, in parse
    return [
  File ".venv\lib\site-packages\aws_lambda_powertools\utilities\parser\envelopes\dynamodb.py", line 39, in <listcomp>
    "NewImage": self._parse(data=record.dynamodb.NewImage, model=model),
  File ".venv\lib\site-packages\aws_lambda_powertools\utilities\parser\envelopes\base.py", line 41, in _parse
    return model.parse_obj(data)
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Item
id
  str type expected (type=type_error.str)
value
  value is not a valid integer (type=type_error.integer)
```

**Comment by leandrodamascena** [comment]
Hello @stpsomad! Thanks for opening this issue and reporting a possible bug. Looking at the code, I see that this is actually not a bug, this is expected behavior when parsing events using a model. I'll go through the code to explain the behavior.

**1 - Payload**

In the payload, `NewImage` keys are a dict, so Pydantic expects a dict instead of a str or int. It could be `str` or `int` if we deserialize the `NewImage` values, but we don't do that in the parser. We just did this in the Event Source Data Class utility.

**2 - Pydantic Model**

You can keep the same model, but you need to add a validator to deserialize and transform the values in `str` or `int`. As I mentioned, we do this in the Event Source and you can use the same function. See this example:

```python
from aws_lambda_powertools.utilities.parser import (
    parse,
    BaseModel,
    envelopes,
)

from aws_lambda_powertools.utilities.data_classes.dynamo_db_stream_event import TypeDeserializer

from pydantic import validator

payload = {...the payload...}

class Item(BaseModel):
    id: str
    value: int

    @validator("id", "value", pre=True, allow_reuse=True)
    def data_decode(cls, values):
        deserialized = TypeDeserializer().deserialize(values)
        return deserialized

parsed_event = parse(model=Item, envelope=envelopes.DynamoDBStreamEnvelope, event=payload)

```
The output will be:
`[{'NewImage': Item(id='key1', value=1), 'OldImage': None}]`

**3 - Next steps**

Deserializing DynamoDB keys in the parser utility is an important issue we need to fix in Powertools, but unfortunately we can't do that right now because it's a breaking change for customers who expect these keys as a dict.
I'll add this feature in our backlog to add this support in Powertools V3.

Please let me know if you need to clarify anything else or need help to adapt your code to make it work.

**Comment by stpsomad** [comment]
@leandrodamascena thanks for your detailed answer. I did not know it was intended. I did not think of using the type deserioliazer.

Wouldn't it be a good idea to have this in the docs?
