### ISSUE TITLE
Typing: Getting type errors on logger usage

### ISSUE THREAD

**Issue by mew1033** [awslabs/aws-lambda-powertools-python#3171]
### Expected Behaviour

We should be able to use `logger.info("log message: %s", "text")` without type errors.

### Current Behaviour

Currently, when logging with the powertools logger, I get the following type error in pylance/pyright:

```
Type of "info" is partially unknown
  Type of "info" is "(msg: object, *args: Unknown, exc_info: Unknown | None = None, stack_info: bool = False, stacklevel: int = 2, extra: Mapping[str, object] | None = None, **kwargs: Unknown) -> None"Pylance[reportUnknownMemberType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)
```

### Code snippet

```python
from aws_lambda_powertools.logging import Logger

logger = Logger()
logger.info("logging logs %s", "text")
```

### Steps to Reproduce

Any of the logging level functions issues the same error.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

PyPi

**Comment by heitorlessa** [comment]
Thanks a lot for creating this issue @mew1033 - I've downgraded as a static typing issue. 

Please correct us if you meant you're getting errors at runtime when running lazy string formatting with Logger - that would be a bug. 

Leaving as triage to try and replicate.

**Comment by heitorlessa** [comment]
Had a quick test with `mypy` and couldn't find an issue. No issue with the latest VSCode either. I'll install pyright directly to test and investigate later.

<img width="1342" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/0d750423-0eaf-4466-a2ee-ee0e6bed06c8">

<img width="635" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/66066233-b669-410f-902d-667a18822ca3">

**Comment by leandrodamascena** [comment]
If I enable `reportUnknownMemberType` check, Pylance complains about the same error.

![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/180ce64c-e149-44a2-8e49-0b6293c9fa2c)

I think we need to add more support for strict typing in some utilities, but in my opinion, we should try to start fixing them in Powertools v3.

**Comment by heitorlessa** [comment]
Got the same now after I enabled strict mode -- I wouldn't however commit to provide support for `strict` mode. It never ends well with a library due to the dynamism in areas we don't fully control or can't have typed it for the behaviour.

For example, it's complaining about the lack of types that actually is an override for the standard logging library. If we run pyright with strict mode against CPython standard logging library it gives the same error.

If anyone knows how we can solve it, please shout out, otherwise I'd defer to the Pyright team to suggest a solution. We will stick to non-strict and Mypy for now

<img width="683" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/c44221bb-709c-442b-866b-8b1ff92310d0">

---


```toml
[tool.pyright]
include = ["powertools-issue-3171"]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.9"
venvPath = ".venv"
typeCheckingMode = "strict"

```
