### ISSUE TITLE
Docs: In the SAM template, BinaryMediaTypes and CORS do not work together

### ISSUE THREAD

**Issue by martinber** [awslabs/aws-lambda-powertools-python#3373]
### What were you searching in the docs?

How to configure CORS

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#required-resources

### How can we improve?

If I'm not wrong, when configuring CORS in the `template.yml` of AWS SAM, CORS doesn't work if `BinaryMediaTypes` is set. [See this issue](https://github.com/aws/serverless-application-model/issues/1344).

The example in the documentation has both CORS and `BinaryMediaTypes` configured. I just copied this example without thinking much and I was surprised to see that it doesn't work. I think that at least a note should be added somewhere to indicate that these two are incompatible.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by heitorlessa** [comment]
hey @martinber sad to hear you bumped into a known issue in SAM exacerbated by our incorrect docs. We'll add a note and push a doc rebuild by EOD, and give the SAM team a heads up about it.

Thank you @martinber for flagging this to us, truly.

**NOTE**: I'll read the entire thread to make sure I fully understand whether this is an API Gateway, SAM or SAM CLI limitation, and document accordingly. If there's a known workaround, we'll update the template too.

**Comment by heitorlessa** [comment]
> **NOTE**: This is not an issue in Powertools for AWS Lambda. We handle runtime.

Tested and here's a summary for anyone coming in later on the issue:

1. API Gateway Pre-flight (`OPTIONS`) gets confused with `*/*` binary and believes all responses are binary
2. Setting each individual mime types work however this can be problematic for customers receiving arbitrary set of binaries

**Action**. Adding a comment in the template **and** in the Binary section to highlight this limitation in API Gateway.

**workaround**

You could use API Gateway as a passthrough for pre-flight requests by configuring it to send `OPTIONS` requests to Lambda function. You [can use `@app.route(".*", method="OPTIONS")`](https://github.com/aws-powertools/powertools-lambda-python/blob/8e0ab8cd75c963ee77ab8b8dc3652fe56e38e576/tests/functional/event_handler/test_api_gateway.py#L747) - that way you have full control of pre-flight logic.

We don't document it yet because by default as ~90% of the time API Gateway handles just fine, and this can create confusion. This is typically used as a workaround for another issue - e.g., multi-origin.

**Comment by heitorlessa** [comment]
PR created. Added the following notes in three places, along with an example of a stricter mime type if CORS must be used:

1. Warning in Binary response section
2. Getting started SAM template
3. Micro-function SAM template

Releasing shortly along with other bugfixes today.

<img width="1153" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/a184f17e-ba63-4101-b19c-148e2ce10762">


<img width="1393" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/23ed5a21-fc9d-45e1-931f-a97a59aa7bbf">

**Comment by martinber** [comment]
Thank you! This is more than enough for me

**Comment by heitorlessa** [comment]
Merged, gonna prep a release now so nobody else bumps into this (hopefully). If we get yet another customer, I'll personally create a complete workaround example to handle CORS along with caveats.

Thank you one more time @martinber for taking the time to report this. We appreciate your care on making everyone's experience better!
