### ISSUE TITLE
Docs: Invalid return type in middleware example

### ISSUE THREAD

**Issue by kamilturek** [awslabs/aws-lambda-powertools-python#3556]
### What were you searching in the docs?

All examples on [the middleware factory page](https://docs.powertools.aws.dev/lambda/python/latest/utilities/middleware_factory/) present a middleware function with return type of `Callable` which seems incorrect.

<img width="626" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/22010517/f16a6ad1-9843-407b-83d4-4c0e8039e29f">

The actual return type of the `middleware_before` function is the same as the one of the lambda handler - `dict` this case. Only after the function is decorated, it'll be a `Callable` but I believe the function definition should anyway have the return type of `dict`.

A small reproducible example:
```python3
from typing import Callable

from aws_lambda_powertools.middleware_factory import lambda_handler_decorator

LambdaHandler = Callable[[dict, dict], dict]


@lambda_handler_decorator
def middleware_add_headers(
    handler: LambdaHandler, event: dict, context: dict
) -> Callable:
    return handler(event, context)


@middleware_add_headers
def lambda_handler(event: dict, context: dict) -> dict:
    return {
        "statusCode": 200,
        "body": "hello",
    }
```
Mypy output:
```
$ mypy main.py
handler.py:12: error: Incompatible return value type (got "dict[Any, Any]", expected "Callable[..., Any]")  [return-value]
Found 1 error in 1 file (checked 1 source file)
```

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/utilities/middleware_factory/#middleware-with-before-logic

### How can we improve?

All invalid examples should be updated with correct return types (seems like `dict` in all cases).

### Got a suggestion in mind?

I'm happy to help with resolving this issue.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by leandrodamascena** [comment]
Hello @kamilturek! Thanks for opening this issue! Static type checking in Python is sometimes challenging.

We use `mypy` to check files in the `aws_lambda_powertools` and `examples` folders and if any file has a problem with static checking, our CI fails, but in this case, it doesn't fail and I was inquisitive about this.

I'm not the biggest mypy expert out there, but from what I understand, our examples don't fail because we're not noting typing the `handler` parameter in `middleware_add_headers`, and as a result, `mypy` can't correctly infer the type of the return from this execution. I changed one of the examples so that `lambda_handler` has a more specific type (just like you) and now I can catch the error.

Would you like to open a PR to fix this? We try to make our documentation as assertive as possible for our customers; this case is certainly something we need to fix quickly.

thanks.

**Comment by kamilturek** [comment]
Hey @leandrodamascena, thanks for looking into this and verifying my report.

I'd be very happy to create a PR. Will do it soon.

Thanks.
