### ISSUE TITLE
Feature request: Add ability to download OpenAPI spec

### ISSUE THREAD

**Issue by Thomas-McKanna** [awslabs/aws-lambda-powertools-python#3560]
### Use case

The Swagger UI feature is nice, but it would be even better to be able to download the OpenAPI specification file so that if users would like to render the documentation in alternative formats, they are easily able to do so.

### Solution/User Experience

This could be achieved by adding another endpoint when Swagger is enabled at `/swagger.json` which would download the spec file.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @Thomas-McKanna! Thanks for the feedback on this feature, we launched it weeks ago and this kind of feedback helps us understand what is still missing in this new utility.

To allow the customer download the OpenAPI definition we must use the `url` parameter instead of using `spec` parameter when [configuring SwaggerUI](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), and today we generate the spec [on-the-fly](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/event_handler/openapi/swagger_ui/html.py#L44) using the `spec` field.

It will be possible if we create a new endpoint for `/swagger.json` (for example) and add a flag to let the customer decide whether or not to enable this endpoint when [enabling swagger](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/event_handler/api_gateway.py#L1546).

I believe this is a great improvement on the OpenAPI feature. We will be very happy if you want to work on this and send a PR as a contribution. 

Thanks

**Comment by Thomas-McKanna** [comment]
@leandrodamascena Sounds good. I will work on a PR.

**Comment by Thomas-McKanna** [comment]
PR created: https://github.com/aws-powertools/powertools-lambda-python/pull/3571
