### ISSUE TITLE
Bug: Can't install with pyndantic >2.0 (despite documentation saying otherwise)

### ISSUE THREAD

**Issue by xaviernogueira** [awslabs/aws-lambda-powertools-python#3601]
### Expected Behaviour

I was expecting to be able to install the Python parser extension of the powertools despite needing pydantic 2.0 after reading the docs [here](https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/).

### Current Behaviour

I am blocked from installing due to conflicting dependencies. The source of the issue is `pyproject.toml`.

If this is unintentional behavior, can you update the `pyproject.toml` requirements, otherwise you should correct the documentation. I may make a PR.

### Code snippet

```python
ERROR: Cannot install -r requirements-runtime.txt (line 4), aws-lambda-powertools[all]==2.31.0 and pydantic>=2.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic>=2.0.3
    geojson-pydantic 1.0.1 depends on pydantic~=2.0
    aws-lambda-powertools[all] 2.31.0 depends on pydantic<2.0.0 and >=1.8.2; extra == "parser" or extra == "all"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Steps to Reproduce

pydantic>=2.0.3
aws_lambda_powertools[all]==2.31.0
boto3==1.26.19
geojson-pydantic==1.0.1

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.10

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Hey @xaviernogueira! Thanks for opening this issue! The reason you can't install Pydantic 2+ is because you are using aws_lambda_powertools[all] and Pydantic v1 is the default version in Powertools.

Pls update your requirements.txt to use aws_lambda_powertools[aws-xray-sdk, fastjsonschema] and then you can bring Pydanticv2.

Pls let me know if this works.

Thanks

**Comment by leandrodamascena** [comment]
I'm closing this issue and feel free to reopen it if necessary @xaviernogueira!

Thanks

**Comment by xaviernogueira** [comment]
@leandrodamascena 

So I tried your solution and got the warning:
```
WARNING: aws-lambda-powertools 2.31.0 does not provide the extra 'aws-xray-sdk'
WARNING: aws-lambda-powertools 2.31.0 does not provide the extra 'fastjsonschema'
```

I can't tell if those extras are installed, but it did allow me to resolve the environment!

That said you guys should consider supporting pydantic 2.0, I may look into making a PR.

**Comment by leandrodamascena** [comment]
Hello @xaviernogueira! My apologies here, I wrote the wrong command! You can try: `pip install "aws_lambda_powertools[validation,tracer]"`

We support Pydantic v2, but we do not make Pydantic v2 our default version because we can break customers who already use Powertools in their apps, and have not yet migrated their code from Pydantic v1 to v2.

We will drop support for Pydanticv1 and make Pydanticv2 the default version in Powertools V3 (we don't have a release estimate yet).

Thanks

**Comment by xaviernogueira** [comment]
@leandrodamascena Thanks for the quick response! I'll let you know how it goes.

**Comment by xaviernogueira** [comment]
Worked!

**Comment by leandrodamascena** [comment]
Thanks for letting me know @xaviernogueira! Feel free to ping us or open issues whenever you need!
