### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'pydantic'

### ISSUE THREAD

**Issue by tonnico** [awslabs/aws-lambda-powertools-python#4498]
### Expected Behaviour

`pydantic` shouldn't be mandatory for default usage, as in `<=2.38.1`.

### Current Behaviour

A `ModuleNotFoundError` is raised.

### Code snippet

```python
from aws_lambda_powertools.event_handler import Response
```

### Steps to Reproduce

```bash
pip install aws-lambda-powertools
cat << EOF >> foo.py
from aws_lambda_powertools.event_handler import Response
EOF
python foo.py
```

### Powertools for AWS Lambda (Python) version

2.39.0

### AWS Lambda function runtime

3.12

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Looking at this now.

**Comment by heitorlessa** [comment]
it's a regression not caught by tests - we're making a fix and a patch release now

**Comment by heitorlessa** [comment]
2.39.0 release yanked, merged regression fix, and we're starting a patch release now.

**Comment by heitorlessa** [comment]
@Wurstnase 2.39.1 is now live in PyPi; we're testing locally with a new project to be sure too. Lambda Layers are starting now

**Edit**: @leandrodamascena just tested in a new project and worked. Let us know otherwise please.

---

Release pipeline as it's public: https://github.com/aws-powertools/powertools-lambda-python/actions/runs/9501863707

**Comment by heitorlessa** [comment]
reopening to make sure we hear back from @Wurstnase

**Comment by tonnico** [comment]
Thanks! Everything is working again.
