### ISSUE TITLE
Bug: Base HTTP gateway resolver sample fails

### ISSUE THREAD

**Issue by andreacfm** [awslabs/aws-lambda-powertools-python#5321]
### Expected Behaviour

The error happens both with 3.0.0 than with 2.43.1

### Current Behaviour

The base sample from the handler docs for Api HTTP Gateway returns the following 500 error.
```
[ERROR] KeyError: 'http'
Traceback (most recent call last):
  File "/var/task/app.py", line 26, in lambda_handler
    return app.resolve(event, context)
  File "/var/task/aws_lambda_powertools/event_handler/api_gateway.py", line 2100, in resolve
    response = self._resolve().build(self.current_event, self._cors)
  File "/var/task/aws_lambda_powertools/event_handler/api_gateway.py", line 2194, in _resolve
    method = self.current_event.http_method.upper()
  File "/var/task/aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py", line 317, in http_method
    return self.request_context.http.method
  File "/var/task/aws_lambda_powertools/utilities/data_classes/common.py", line 467, in method
    return self["requestContext"]["http"]["method"]
```

### Code snippet

```import requests
from requests import Response

from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import APIGatewayHttpResolver
from aws_lambda_powertools.logging import correlation_paths
from aws_lambda_powertools.utilities.typing import LambdaContext

tracer = Tracer()
logger = Logger()
app = APIGatewayHttpResolver()


@app.get("/todos")
@tracer.capture_method
def get_todos():
    todos: Response = requests.get("https://jsonplaceholder.typicode.com/todos")
    todos.raise_for_status()

    # for brevity, we'll limit to the first 10 only
    return {"todos": todos.json()[:10]}


# You can continue to use other utilities just as before
@logger.inject_lambda_context(correlation_id_path=correlation_paths.API_GATEWAY_HTTP)
@tracer.capture_lambda_handler
def lambda_handler(event: dict, context: LambdaContext) -> dict:
    return app.resolve(event, context)
```

### Steps to Reproduce

Deploy the lambda and executed the /todos request using an HTTP gateway.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.8

### Packaging format used

PyPi

**Comment by leandrodamascena** [comment]
Ciao @andreacfm, thanks for opening this issue! I couldn't reproduce the error and I'm wondering if you are using Payload v1.0 in this integration. You should use Payload v2.0 to use this Resolver. Payload v1.0 is supported in `APIGatewayRestResolver`, but I recommend you to use Payload v2.0 in HTTP API.

I would also like to ask if you are using Terraform to deploy this workload, because this is a [known issue](https://github.com/hashicorp/terraform-provider-aws/issues/37035) that Terraform defaults to Payload v1.0 if the version is not provided.

![Image](https://github.com/user-attachments/assets/08c35564-49c8-496f-9645-dcbd26dcf96f)


Please let me know if changing the version fixed the problem and if I can help with anything else.

**Comment by andreacfm** [comment]
@leandrodamascena my bad. I was using 1.0 payloads. Thanks for checking in.
