### ISSUE TITLE
Bug: Pydantic "escape hatch" no longer available

### ISSUE THREAD

**Issue by areifert** [awslabs/aws-lambda-powertools-python#5352]
### Expected Behaviour

The Parser documentation FAQ states that an "escape hatch" mechanism can be used to access imports from the base `pydantic` library that are not otherwise available as imports from `aws_lambda_powertools.utilities.parser`: https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/#faq.

### Current Behaviour

`aws_lambda_powertools.utilities.parser.pydantic` is not a valid import path. (This may have been an older feature that has since been removed.)

### Code snippet

from aws_lambda_powertools.utilities.parser.pydantic import <what you'd like to import'>

### Possible Solution

If all `pydantic` imports can be made available at `aws_lambda_powertools.utilities.parser.pydantic` (likely by modifying [aws_lambda_powertools/utilities/parser/\_\_init__.py](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/utilities/parser/__init__.py)), that would be ideal. Otherwise, the documentation should be updated to remove this feature.

### Steps to Reproduce

Attempting to import anything from `aws_lambda_powertools.utilities.parser.pydantic` will result in an import error.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.12

### Packaging format used

Lambda Layers

**Comment by areifert** [comment]
For reference, I was trying to import `computed_field`, but
```python
from aws_lambda_powertools.utilities.parser import computed_field
```
is not a valid import.

**Comment by leandrodamascena** [comment]
Hey @areifert thanks a lot for opening this issue! In fact we are not exporting Pydantic objects from parser and we explain that in our [upgrade guide](https://docs.powertools.aws.dev/lambda/python/latest/upgrade/#importing-pydantic-objects) to v3.

In Powertools v3 we have dropped support for Pydantic v1 and are only supporting Pydantic v2 which is why we are no longer exporting pydantic types directly and allowing customers to import them directly from Pydantic. First, I must say that I agree with that we need to update our documentation and we are [already doing this](https://github.com/aws-powertools/powertools-lambda-python/pull/5262). I'll try to merge this PR as soon as possible to prevent this type of error. 

Let me explain some reasons why we removed this export:

1 - Pydantic V2 was a complete refactoring of the Pydantic project and they made several changes including, but not limited, to the way they export types, classes, methods, and others. If we continue to expose them directly from Powertools and some export in Pydantic has changed, our customers may get the impression that there is some bug in Powertools and that is not the experience we want to have for our customers.

2 - The way we were doing this was by [exposing everything](https://github.com/aws-powertools/powertools-lambda-python/blob/v2/aws_lambda_powertools/utilities/parser/pydantic.py) exposed from pydantic to our customers, but there is a long discussion in the Pydantic repository about how https://github.com/pydantic/pydantic/discussions/6748 when importing and loading things in this new version. We don't want our customers to inadvertently import everything from Pydantic and this could create some slowdown in their functions.

Can you please try importing them directly from Pydantic?

**Comment by areifert** [comment]
@leandrodamascena: this is perfect, thanks for the detailed response. I was able to import `computed_field` directly from Pydantic.

It looks like some Pydantic exports are still available from `aws_lambda_powertools.utilities.parser` (e.g., `BaseModel`); going forward, is it recommended that all of these be imported directly from Pydantic instead?

(P.S.: I've been using Powertools for only a month or two and am really enjoying it, thanks for all you do!)

**Comment by leandrodamascena** [comment]
> 
> It looks like some Pydantic exports are still available from `aws_lambda_powertools.utilities.parser` (e.g., `BaseModel`); going forward, is it recommended that all of these be imported directly from Pydantic instead?

This is expected because now we just export `BaseModel`, `Field`, `ValidationError`, `field_validator`, and `model_validator`, the functions/classes that we must use in our utilities, including parser. The old way we were exporting  * from pydantic and errors.

> 
> (P.S.: I've been using Powertools for only a month or two and am really enjoying it, thanks for all you do!)

Hey, that's awesome to hear! We're here to support you in any way you need. Feel free to open an issue or talk to us on our Discord server https://discord.gg/B8zZKbbyET

Closing this issue.
