### ISSUE TITLE
Feature request: Add `pydantic-settings` to v3 Layer

### ISSUE THREAD

**Issue by tkasuz** [awslabs/aws-lambda-powertools-python#5508]
### Use case

To facilitate migration from v2 to v3, it would be advantageous to include `pydantic-settings` as an optional dependency in the v3 layer. This is because v3 relies on Pydantic v2, necessitating the import of BaseSettings from `pydantic-settings`, which is currently absent from the v3 layer.

### Solution/User Experience

Since this is not directly related to `parser` library, it would be better to included in the all option like the following:

```toml
[tool.poetry.extras]
parser = ["pydantic"]
validation = ["fastjsonschema"]
tracer = ["aws-xray-sdk"]
redis = ["redis"]
all = [
  "pydantic",
  "pydantic-settings",
  "aws-xray-sdk",
  "fastjsonschema",
  "aws-encryption-sdk",
  "jsonpath-ng"
]
```

### Acknowledgment

- [x] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

**Comment by leandrodamascena** [comment]
Hi @tkasuz! Thanks for raising this issue! I agree with you that this might make the migration from Powertools v2 to v3 easier for those who are building Lambda exclusively with Powertools layers and not installing anything with `pip`. Even Pydantic v2 changed the way `BaseSettings` is imported and force you change your code, I think it might make life easier for those who are migrating. I don't think this is a big issue from a performance/size perspective, because both `pydantic_settings` and `dotenv` (transitive dependency) are less than 500kb.

```
(venv) ➜ du -sh venv/lib/python3.12/site-packages/*dotenv* 
116K	venv/lib/python3.12/site-packages/dotenv
 48K	venv/lib/python3.12/site-packages/python_dotenv-1.0.1.dist-info
(venv) ➜ du -sh venv/lib/python3.12/site-packages/pydantic_settings*
276K	venv/lib/python3.12/site-packages/pydantic_settings
 20K	venv/lib/python3.12/site-packages/pydantic_settings-2.6.1.dist-info
(venv) ➜  
```

Can you please send a PR to add this support?
