### ISSUE TITLE
configure standard python logging

### ISSUE THREAD

**Issue by houbie** [awslabs/aws-lambda-powertools-python#836]
**What were you initially searching for in the docs?**
I want to turn on logging of (3th party) libraries that use standard logging.

**Is this related to an existing part of the documentation? Please share a link**
The [FAQ](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/logger/#faq) explains how to enable logging for boto3, but not for other libraries using standard logging.

**Describe how we could make it clearer**
* How should one configure standard logging to make it available in cloudwatch?
* Is it possible to output standard logs in the same way as the power tools logger (structured logs)?

**Comment by heitorlessa** [comment]
hey @houbie - thanks for reaching out! We have that on the roadmap and will start working on it next week: https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/40

As a common practice, every library should define a way to enable its logging and should be disabled by default with no formatting. 

Since this is becoming a common feature request (please add +1 there), we'll add a new method which will allow you to copy Powertools Logger to any registered Python logging library. This method will allow you to specify the 3rd party libraries ones you don't want to touch, and we will set the same or different Log Level **and** same JSON formatting you are using in Powertools Logger.

Please do reopen if I misunderstood it completely.

Thanks!
