### ISSUE TITLE
How to create a custom log level

### ISSUE THREAD

**Issue by jonathan-kosgei** [awslabs/aws-lambda-powertools-python#846]
I'm using the logger in my project and I'd like to print a line of json for post-processing without the powertools logger adding context to it. How would I do this?

**Comment by heitorlessa** [comment]
Hi @jonathan-kosgei - as the issue was created without the template, we'll need more context to understand what you're trying to do.

Could you expand on what you mean by "without Powertools adding context"?

Could you share the desired log output you'd like when printing this one line of JSON?

Thank you

**Comment by jonathan-kosgei** [comment]
@heitorlessa thanks for getting back to me so fast. I just realized this was a mistake on my part as the added context i.e. timestamp, log group, function attributes etc were added by datadog and not powertools. I'll go ahead and close the issue, thanks again.
