### ISSUE TITLE
docs: Add support and build instructions and workflows for arm64

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-python#979]
**Is your feature request related to a problem? Please describe.**

Now that arm64 architecture is official for lambdas, we should ensure Powertools works perfectly well and have a guide on how to take advantage of this feature via SAM and CDK.

**Describe the solution you'd like**

Update docs and test automation to include arm64

**Describe alternatives you've considered**

**Additional context**

**Comment by heitorlessa** [comment]
Ref https://github.com/GrahamDumpleton/wrapt/issues/198 as pointed out by @eldritchideen, since we depend on X-Ray SDK this won't likely be possible with SAM CLI (maybe via Makefile but suboptimal), but a custom Lambda Layer.

**Comment by eldritchideen** [comment]
I have also commented on what appears to be the root cause in the Pip builder that SAM uses to package the dependencies here. https://github.com/aws/aws-lambda-builders/issues/302 

The wheel for wrapt gets built correctly, however as the file name has "linux" rather than "manylinux" it is rejected as not compatible.

**Comment by eldritchideen** [comment]
This example repo shows how to work around the issue of Arm dependencies that require sdist builds with C extensions failing by packaging them in a layer. 
https://github.com/eldritchideen/arm-python-lambda-example
